#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

	[0]=LAYOUT(
        KC_ESC, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12,
		KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSLS, KC_DEL,
		KC_CAPS, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_BSPC, KC_ENT, KC_GRV,
		KC_LSFT, KC_Z, KC_X, KC_V, KC_C, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_RSFT,
		KC_LCTL, KC_LGUI, KC_LALT, MO(1), KC_SPC, LT(2,KC_ENT), LT(3,KC_LEFT), KC_UP, KC_DOWN, KC_RGHT, KC_PGUP, KC_PGDN),
    [1]=LAYOUT(
		KC_GRV, KC_TILD, KC_LABK, KC_RABK, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_COMM, KC_DOT, KC_TRNS, KC_TRNS,
		KC_LPRN, KC_QUES, KC_HASH, KC_AMPR, KC_DLR, KC_EXLM, KC_PERC, KC_7, KC_8, KC_9, KC_AT, KC_BSLS, LCTL(LALT(KC_DEL)),
		KC_LBRC, KC_SCLN, KC_DQUO, KC_PLUS, KC_MINS, KC_PIPE, KC_EQL, KC_4, KC_5, KC_6, KC_UNDS, KC_RBRC, KC_RPRN,
		KC_LCBR, KC_COLN, KC_QUOT, KC_ASTR, KC_SLSH, KC_CIRC, KC_0, KC_1, KC_2, KC_3, KC_RCBR,
		KC_LCTL, KC_LSFT, KC_LALT, KC_TRNS, LT(5,KC_SPC), LT(2,KC_ENT), LT(3,KC_BSPC), KC_DEL, KC_RSFT, KC_RCTL, KC_PSCR, KC_INS),
    [2]=LAYOUT(
		LCTL(LSFT(KC_ESC)), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TAB, KC_MS_BTN4, KC_MS_BTN5, KC_MS_UP, LCTL(KC_R), LCTL(KC_T), LCTL(KC_Y), KC_MS_ACCEL0, KC_UP, KC_PGUP, KC_MS_ACCEL1, KC_MS_ACCEL2, LCTL(LALT(KC_DEL)),
		KC_MS_BTN2, KC_MS_BTN1, KC_MS_LEFT, KC_MS_DOWN, KC_MS_RIGHT, KC_BSPC, KC_DEL, KC_LEFT, KC_DOWN, KC_RGHT, KC_PGDN, LCTL(KC_ENT), LCTL(KC_PSCR),
		KC_LSFT, LCTL(KC_Z), LCTL(KC_X), LCTL(KC_V), LCTL(KC_C), LCTL(KC_B), KC_HOME, KC_END, LSFT(KC_HOME), LSFT(KC_END), KC_RSFT,
		KC_LCTL, KC_LGUI, KC_LALT, KC_ENT, KC_SPC, KC_TRNS, KC_MUTE, KC_VOLU, KC_VOLD, KC_MPLY, KC_RALT, KC_RCTL),
	[3]=LAYOUT(
		LCTL(LSFT(KC_ESC)), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, LCTL(KC_Q), LCTL(KC_W), LCTL(KC_E), LCTL(KC_R), LCTL(KC_T), LCTL(KC_Y), LCTL(KC_U), LCTL(KC_I), LCTL(KC_O), LCTL(KC_P), LCTL(KC_SLSH), LCTL(LALT(KC_DEL)),
		KC_TRNS, LCTL(KC_A), LCTL(KC_S), LCTL(KC_D), LCTL(KC_F), LCTL(KC_G), LCTL(KC_H), LCTL(KC_J), LCTL(KC_K), LCTL(KC_L), KC_DEL, LCTL(KC_ENT), LCTL(KC_PSCR),
		KC_TRNS, LCTL(KC_Z), LCTL(KC_X), LCTL(KC_V), LCTL(KC_C), LCTL(KC_B), LCTL(KC_N), LCTL(KC_M), LSFT(KC_HOME), LSFT(KC_END), KC_RSFT,
		KC_TRNS, KC_TRNS, KC_TRNS, MO(4), LCTL(KC_SPC), KC_ENT, KC_TRNS, KC_VOLU, KC_VOLD, KC_MPLY, KC_RALT, KC_RCTL),
    [4]=LAYOUT(
		QK_BOOT, DB_TOGG, EE_CLR, QK_MAKE, QK_RBT, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TAB, KC_MS_BTN4, KC_MS_BTN5, KC_MS_UP, LCTL(KC_R), LCTL(KC_T), LCTL(KC_Y), KC_MS_ACCEL0, KC_MS_WH_UP, KC_PGUP, KC_MS_ACCEL1, KC_MS_ACCEL2, LCTL(LALT(KC_DEL)),
		KC_CAPS, KC_TRNS, KC_MS_LEFT, KC_MS_DOWN, KC_MS_RIGHT, KC_BSPC, KC_DEL, KC_LEFT, KC_DOWN, KC_RGHT, KC_PGDN, LCTL(KC_ENT), KC_TRNS,
		KC_LSFT, LCTL(KC_Z), LCTL(KC_X), LCTL(KC_V), LCTL(KC_C), LCTL(KC_B), KC_HOME, KC_END, LSFT(KC_HOME), LSFT(KC_END), KC_RSFT,
		KC_LCTL, KC_LGUI, KC_LALT, KC_ENT, KC_SPC, KC_TRNS, KC_MUTE, KC_VOLU, KC_VOLD, KC_MPLY, KC_RALT, KC_RCTL),
	[5]=LAYOUT(
        KC_ESC, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12,
		KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSLS, KC_DEL,
		KC_CAPS, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_BSPC, KC_ENT, KC_GRV,
		KC_LSFT, KC_Z, KC_X, KC_V, KC_C, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_RSFT,
		KC_LCTL, KC_LGUI, KC_LALT, KC_TRNS, KC_SPC, KC_TRNS, KC_LEFT, KC_UP, KC_DOWN, KC_RGHT, KC_PGUP, KC_PGDN)
};
